name: vtadmin-web build
run-name: Running first party validation for ${{ inputs.chosen-runner }}
on:
  workflow_dispatch:
    inputs:
      chosen-runner:
        required: true
        type: choice
        options:
        - alex-arm64-linux
        - alex-arm64-windows
        - 4-core-ubuntu-benchmark-perf-test
        - 8-core-windows-benchmark-perf-test


permissions: read-all

jobs:
  build:
    runs-on: gh-hosted-runners-4cores-1
    steps:
      - name: Skip CI
        run: |
          if [[ "${{contains( github.event.pull_request.labels.*.name, 'Skip CI')}}" == "true" ]]; then
            echo "skipping CI due to the 'Skip CI' label"
            exit 1
          fi

      - name: Check if workflow needs to be skipped
        id: skip-workflow
        run: |
          skip='false'
          if [[ "${{github.event.pull_request}}" ==  "" ]] && [[ "${{github.ref}}" != "refs/heads/main" ]] && [[ ! "${{github.ref}}" =~ ^refs/heads/release-[0-9]+\.[0-9]$ ]] && [[ ! "${{github.ref}}" =~ "refs/tags/.*" ]]; then
          skip='true'
          fi
          echo Skip ${skip}
          echo "skip-workflow=${skip}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v3
        if: steps.skip-workflow.outputs.skip-workflow == 'false'

      - uses: actions/setup-node@v3
        if: steps.skip-workflow.outputs.skip-workflow == 'false'
        with:
          # node-version should match package.json
          node-version: '18.16.0'

      - name: Install dependencies
        if: steps.skip-workflow.outputs.skip-workflow == 'false'
        run: cd ./web/vtadmin && npm ci

      - name: Build front-end
        if: steps.skip-workflow.outputs.skip-workflow == 'false'
        run: cd ./web/vtadmin && npm run build

    # Cancel pending and in-progress runs of this workflow if a newer ref is pushed to CI.
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
